INSERT INTO sections (id, area_id, code, name, display_order) VALUES 
('area_parkir_sec_a', 'area_parkir', 'A', 'Paving & Jalur Masuk', 65),
('area_parkir_sec_b', 'area_parkir', 'B', 'Area Parkir Motor', 66),
('area_parkir_sec_c', 'area_parkir', 'C', 'Area Parkir Mobil', 67),
('area_parkir_sec_d', 'area_parkir', 'D', 'Dinding, Pagar & Plang Depan', 68),
('area_parkir_sec_e', 'area_parkir', 'E', 'Tempat Sampah & Pemilahan', 69),
('area_parkir_sec_f', 'area_parkir', 'F', 'Drainase & Saluran Pembuangan', 70),
('area_parkir_sec_g', 'area_parkir', 'G', 'Depan Gedung & Teras Luar', 71),
('area_fo_bts_sec_a', 'area_fo_bts', 'A', 'Pintu Masuk & Foyer BTS', 65),
('area_fo_bts_sec_b', 'area_fo_bts', 'B', 'Meja Customer Service & Kasir', 66),
('area_fo_bts_sec_c', 'area_fo_bts', 'C', 'Area Tunggu & Kursi Tamu', 67),
('area_fo_bts_sec_d', 'area_fo_bts', 'D', 'Dispenser Air & Refreshment Tamu', 68),
('area_fo_bts_sec_e', 'area_fo_bts', 'E', 'Rak Brosur, Banner & Display', 69),
('area_fo_bts_sec_f', 'area_fo_bts', 'F', 'Branding BTS, BOffice & ASA Rental', 70),
('area_fo_bts_sec_g', 'area_fo_bts', 'G', 'Lantai, Dinding & Plafon FO BTS', 71),
('area_fo_bts_sec_h', 'area_fo_bts', 'H', 'Fasilitas Penunjang & Keamanan', 72),
('area_fo_boffice_sec_a', 'area_fo_boffice', 'A', 'Lantai & Sirkulasi', 65),
('area_fo_boffice_sec_b', 'area_fo_boffice', 'B', 'Reception Desk BOffice', 66),
('area_fo_boffice_sec_c', 'area_fo_boffice', 'C', 'Kursi & Lounge Tamu', 67),
('area_fo_boffice_sec_d', 'area_fo_boffice', 'D', 'Branding BOffice, BLegal & Bali Mediation', 68),
('area_fo_boffice_sec_e', 'area_fo_boffice', 'E', 'Kaca, Pintu & Partisi', 69),
('area_coworking_sec_f', 'area_coworking', 'F', 'Meja Kerja & Workstation', 70),
('area_coworking_sec_g', 'area_coworking', 'G', 'Kursi Kerja Ergonomis', 71),
('area_coworking_sec_h', 'area_coworking', 'H', 'Lantai, Dinding & Akustik', 72),
('area_coworking_sec_i', 'area_coworking', 'I', 'Plafon, Pencahayaan & Storage', 73),
('area_coffee_station_sec_j', 'area_coffee_station', 'J', 'Pantry, Mesin Kopi & Replenishment', 74),
('area_shower_sec_a', 'area_shower', 'A', 'Area Bilas & Shower Kering/Basah', 65),
('area_toilet_sec_a', 'area_toilet', 'A', 'Kebersihan Kloset, Urinoir & Sanitasi', 65)
ON CONFLICT (id) DO NOTHING;

INSERT INTO items (id, section_id, code, text, frequency, weight, is_key_item, require_photo, is_supply, is_active, display_order) VALUES 
('area_parkir_sec_a_item_1', 'area_parkir_sec_a', 'A.1', 'Paving blok bersih dari lumut & rumput liar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_a_item_2', 'area_parkir_sec_a', 'A.2', 'Marking jalur masuk jelas dan rapi', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_parkir_sec_a_item_3', 'area_parkir_sec_a', 'A.3', 'Tidak ada genangan air atau oli', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_a_item_4', 'area_parkir_sec_a', 'A.4', 'Ramp akses motor/mobil mulus tanpa retakan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_a_item_5', 'area_parkir_sec_a', 'A.5', 'Cat batas jalan & polisi tidur terlihat jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_a_item_6', 'area_parkir_sec_a', 'A.6', 'Kondisi penutup got/saluran depan rata', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_a_item_7', 'area_parkir_sec_a', 'A.7', 'Rambu kecepatan & arah masuk tegak & bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_a_item_8', 'area_parkir_sec_a', 'A.8', 'Kebersihan trotoar luar depan gerbang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_a_item_9', 'area_parkir_sec_a', 'A.9', 'Bebas dari puntung rokok & dedaunan kering', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_b_item_1', 'area_parkir_sec_b', 'B.1', 'Garis marka slot parkir motor jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_b_item_2', 'area_parkir_sec_b', 'B.2', 'Motor tersusun rapi sesuai batas garis', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_b_item_3', 'area_parkir_sec_b', 'B.3', 'Lantai bebas ceceran oli motor', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_b_item_4', 'area_parkir_sec_b', 'B.4', 'Stand helm & area penitipan tertata rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_b_item_5', 'area_parkir_sec_b', 'B.5', 'Signage parkir khusus tamu vs staf bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_b_item_6', 'area_parkir_sec_b', 'B.6', 'Tempat sampah area motor kosong & ada plastik', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_b_item_7', 'area_parkir_sec_b', 'B.7', 'Tiang pembatas kokoh tidak goyang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_b_item_8', 'area_parkir_sec_b', 'B.8', 'Kerapian kabel atau pipa di dinding parkir motor', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_b_item_9', 'area_parkir_sec_b', 'B.9', 'Penerangan malam di atas parkir motor berfungsi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_c_item_1', 'area_parkir_sec_c', 'C.1', 'Garis marka slot mobil (tamup, direksi, operasional) tegas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_c_item_2', 'area_parkir_sec_c', 'C.2', 'Stopper roda mobil bersih dan terpasang kuat', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_c_item_3', 'area_parkir_sec_c', 'C.3', 'Bebas tetesan oli atau cairan radiator di paving', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_c_item_4', 'area_parkir_sec_c', 'C.4', 'Kerapian kanopi / peneduh mobil', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_parkir_sec_c_item_5', 'area_parkir_sec_c', 'C.5', 'Signage tarif/aturan parkir terbaca jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_c_item_6', 'area_parkir_sec_c', 'C.6', 'Jalur putar dan manuver mobil bebas hambatan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_c_item_7', 'area_parkir_sec_c', 'C.7', 'Cermin cembung tikungan bersih dan sudut pas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_c_item_8', 'area_parkir_sec_c', 'C.8', 'Penerangan area mobil terang merata', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_d_item_1', 'area_parkir_sec_d', 'D.1', 'Plang nama ASA / BOffice bersih & lampu menyala', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_parkir_sec_d_item_2', 'area_parkir_sec_d', 'D.2', 'Pagar besi bebas karat & rel pintu pagar lancar', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_parkir_sec_d_item_3', 'area_parkir_sec_d', 'D.3', 'Dinding luar bebas coretan dan debu tebal', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_d_item_4', 'area_parkir_sec_d', 'D.4', 'Kondisi cat dinding luar rapi tidak mengelupas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_d_item_5', 'area_parkir_sec_d', 'D.5', 'Plafon kanopi luar bersih dari sarang laba-laba', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_parkir_sec_d_item_6', 'area_parkir_sec_d', 'D.6', 'Lampu sorot fasad gedung menyala optimal', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_d_item_7', 'area_parkir_sec_d', 'D.7', 'Tanaman hias depan terawat & disiram', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_parkir_sec_d_item_8', 'area_parkir_sec_d', 'D.8', 'Kerapian nomor bangunan & papan izin', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_parkir_sec_e_item_1', 'area_parkir_sec_e', 'E.1', 'Tong sampah pilah (Organik, Anorganik, B3) bersih luar dalam', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_e_item_2', 'area_parkir_sec_e', 'E.2', 'Plastik sampah terpasang rapi di dalam tong', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_e_item_3', 'area_parkir_sec_e', 'E.3', 'Tutup tong sampah berfungsi rapat', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_e_item_4', 'area_parkir_sec_e', 'E.4', 'Area sekitar tong sampah tidak bau dan tidak becek', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_e_item_5', 'area_parkir_sec_e', 'E.5', 'TPS sementara tertutup dan rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_e_item_6', 'area_parkir_sec_e', 'E.6', 'Jadwal angkut sampah terpasang dan terpantau', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_e_item_7', 'area_parkir_sec_e', 'E.7', 'Ketersediaan sapu lidi, serokan, dan kantong cadangan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_e_item_8', 'area_parkir_sec_e', 'E.8', 'Bebas dari lalat dan serangga pengganggu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_f_item_1', 'area_parkir_sec_f', 'F.1', 'Grill besi penutup drainase terpasang kokoh & bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_f_item_2', 'area_parkir_sec_f', 'F.2', 'Saluran air lancar tidak ada endapan lumpur/sampah', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_f_item_3', 'area_parkir_sec_f', 'F.3', 'Tidak tercium bau menyengat dari got/drainase', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_f_item_4', 'area_parkir_sec_f', 'F.4', 'Pipa talang air hujan vertikal utuh tidak bocor', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_f_item_5', 'area_parkir_sec_f', 'F.5', 'Bak kontrol air bersih dan saringan tidak mampet', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_f_item_6', 'area_parkir_sec_f', 'F.6', 'Lubang resapan air / biopori berfungsi lancar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_f_item_7', 'area_parkir_sec_f', 'F.7', 'Dinding saluran tidak retak atau bocor ke jalan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_f_item_8', 'area_parkir_sec_f', 'F.8', 'Bebas dari jentik nyamuk dan genangan mati', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_1', 'area_parkir_sec_g', 'G.1', 'Keset luar depan pintu masuk bersih dan kering', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_2', 'area_parkir_sec_g', 'G.2', 'Lantai teras disapu dan dipel bersih mengkilap', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_3', 'area_parkir_sec_g', 'G.3', 'Kaca etalase luar bebas debu & bercak sidik jari', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_4', 'area_parkir_sec_g', 'G.4', 'Tempat payung basah tersedia dan rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_5', 'area_parkir_sec_g', 'G.5', 'Asbak luar bersih dan pasir/air diganti', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_6', 'area_parkir_sec_g', 'G.6', 'Bunga/tanaman pot depan teras daunnya segar', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_7', 'area_parkir_sec_g', 'G.7', 'Bel pintu & intercom berfungsi normal', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_8', 'area_parkir_sec_g', 'G.8', 'Signage petunjuk arah masuk terbaca jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_9', 'area_parkir_sec_g', 'G.9', 'Kamera CCTV outdoor bersih dari debu/sarang laba-laba', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_parkir_sec_g_item_10', 'area_parkir_sec_g', 'G.10', 'READY TO USE: Fasad & Halaman Luar Siap Menerima Tamu', 'all_checkpoints', 2, true, true, false, TRUE, 0),
('area_fo_bts_sec_a_item_1', 'area_fo_bts_sec_a', 'A.1', 'Pintu kaca otomatis/manual bersih tanpa bercak', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_a_item_2', 'area_fo_bts_sec_a', 'A.2', 'Handle pintu higienis dan kokoh', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_a_item_3', 'area_fo_bts_sec_a', 'A.3', 'Keset welcoming kering dan posisinya lurus', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_a_item_4', 'area_fo_bts_sec_a', 'A.4', 'Sensor pintu / bel sambutan berfungsi baik', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_a_item_5', 'area_fo_bts_sec_a', 'A.5', 'Suhu ruangan lobi sejuk (22-24°C)', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_a_item_6', 'area_fo_bts_sec_a', 'A.6', 'Aroma ruangan wangi dan menyegarkan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_a_item_7', 'area_fo_bts_sec_a', 'A.7', 'Hand sanitizer di pintu masuk terisi penuh', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_a_item_8', 'area_fo_bts_sec_a', 'A.8', 'Layar informasi sambutan menyala aktif', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_b_item_1', 'area_fo_bts_sec_b', 'B.1', 'Permukaan meja CS bersih dan bebas debu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_b_item_2', 'area_fo_bts_sec_b', 'B.2', 'Komputer, keyboard, dan mouse tertata rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_b_item_3', 'area_fo_bts_sec_b', 'B.3', 'Kerapian jalur kabel di bawah dan belakang meja', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_b_item_4', 'area_fo_bts_sec_b', 'B.4', 'Mesin EDC dan barcode scanner berfungsi & bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_b_item_5', 'area_fo_bts_sec_b', 'B.5', 'Stempel, pulpen, dan alat tulis tersusun di organizer', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_b_item_6', 'area_fo_bts_sec_b', 'B.6', 'Papan nama petugas CS terpasang rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_b_item_7', 'area_fo_bts_sec_b', 'B.7', 'Kursi petugas bersih dan hidrolik normal', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_b_item_8', 'area_fo_bts_sec_b', 'B.8', 'Laci kasir dan dokumen tertutup rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_c_item_1', 'area_fo_bts_sec_c', 'C.1', 'Sofa / kursi tamu bebas debu dan noda', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_c_item_2', 'area_fo_bts_sec_c', 'C.2', 'Bantal kursi tersusun simetris dan rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_c_item_3', 'area_fo_bts_sec_c', 'C.3', 'Meja kopi tamu bersih tanpa bekas cangkir', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_c_item_4', 'area_fo_bts_sec_c', 'C.4', 'Majalah dan brosur terbaru tersusun rapi di meja', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_c_item_5', 'area_fo_bts_sec_c', 'C.5', 'Stop kontak charging station tamu berfungsi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_c_item_6', 'area_fo_bts_sec_c', 'C.6', 'Karpet area tunggu divakum bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_c_item_7', 'area_fo_bts_sec_c', 'C.7', 'Tempat sampah kecil di samping sofa kosong & berplastik', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_c_item_8', 'area_fo_bts_sec_c', 'C.8', 'Jarak antar kursi proporsional dan leluasa', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_d_item_1', 'area_fo_bts_sec_d', 'D.1', 'Bodi dispenser luar bersih mengkilap tanpa noda air', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_d_item_2', 'area_fo_bts_sec_d', 'D.2', 'Baki penampung tetesan air kosong dan kering', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_d_item_3', 'area_fo_bts_sec_d', 'D.3', 'Kran panas dan dingin berfungsi normal', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_d_item_4', 'area_fo_bts_sec_d', 'D.4', 'Galon air terisi cukup (tidak kosong)', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_d_item_5', 'area_fo_bts_sec_d', 'D.5', 'Cup dispenser terisi gelas bersih / paper cup', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_d_item_6', 'area_fo_bts_sec_d', 'D.6', 'Tempat pembuangan cup bekas bersih dan rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_d_item_7', 'area_fo_bts_sec_d', 'D.7', 'Gula sachet, teh, dan kopi tamu tertata di wadah', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_d_item_8', 'area_fo_bts_sec_d', 'D.8', 'Tisu meja tamu selalu tersedia', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_e_item_1', 'area_fo_bts_sec_e', 'E.1', 'Rak brosur akrilik bersih tidak berdebu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_e_item_2', 'area_fo_bts_sec_e', 'E.2', 'Brosur paket sewa & layanan tersusun rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_e_item_3', 'area_fo_bts_sec_e', 'E.3', 'Roll banner berdiri tegak dan tidak melengkung', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_e_item_4', 'area_fo_bts_sec_e', 'E.4', 'Display merchandise / sampel produk rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_e_item_5', 'area_fo_bts_sec_e', 'E.5', 'Lampu sorot rak display menyala terang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_e_item_6', 'area_fo_bts_sec_e', 'E.6', 'Papan pengumuman/kurs/tarif terupdate', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_e_item_7', 'area_fo_bts_sec_e', 'E.7', 'Brosur usang/rusak sudah disingkirkan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_e_item_8', 'area_fo_bts_sec_e', 'E.8', 'Akrilik QR Code pembayaran QRIS bersih & jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_f_item_1', 'area_fo_bts_sec_f', 'F.1', 'Logo 3D akrilik BTS di dinding bersih mengkilap', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_f_item_2', 'area_fo_bts_sec_f', 'F.2', 'Backdrop lampu LED neon sign menyala sempurna', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_f_item_3', 'area_fo_bts_sec_f', 'F.3', 'Plakat ASA Rental dan kemitraan terpasang lurus', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_f_item_4', 'area_fo_bts_sec_f', 'F.4', 'Stiker branding kaca tidak mengelupas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_f_item_5', 'area_fo_bts_sec_f', 'F.5', 'Frame sertifikat / piagam penghargaan bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_f_item_6', 'area_fo_bts_sec_f', 'F.6', 'Tidak ada kabel signage yang menjuntai liar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_f_item_7', 'area_fo_bts_sec_f', 'F.7', 'Warna cat dinding backdrop bersih merata', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_f_item_8', 'area_fo_bts_sec_f', 'F.8', 'Kerapian display kartu nama representatif', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_g_item_1', 'area_fo_bts_sec_g', 'G.1', 'Lantai granit/vinil dipel bersih berkilau', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_g_item_2', 'area_fo_bts_sec_g', 'G.2', 'List plint dinding sudut bawah bebas debu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_g_item_3', 'area_fo_bts_sec_g', 'G.3', 'Dinding tidak ada noda bercak sepatu atau kotoran', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_g_item_4', 'area_fo_bts_sec_g', 'G.4', 'Plafon gipsum bersih bebas noda rembesan AC', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_g_item_5', 'area_fo_bts_sec_g', 'G.5', 'Semua kisi-kisi AC split/kaset bersih dari jelaga debu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_g_item_6', 'area_fo_bts_sec_g', 'G.6', 'Lampu downlight plafon menyala semua', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_g_item_7', 'area_fo_bts_sec_g', 'G.7', 'Jam dinding tepat waktu dan baterai aktif', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_g_item_8', 'area_fo_bts_sec_g', 'G.8', 'Diffuser aromaterapi menyala mengeluarkan aroma', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_h_item_1', 'area_fo_bts_sec_h', 'H.1', 'APAR tabung pemadam bertekanan normal & segel utuh', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_h_item_2', 'area_fo_bts_sec_h', 'H.2', 'Petunjuk jalur evakuasi terlihat jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_h_item_3', 'area_fo_bts_sec_h', 'H.3', 'CCTV sudut kasir dan lobi beroperasi normal', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_h_item_4', 'area_fo_bts_sec_h', 'H.4', 'Kotak P3K FO terisi obat dasar dan perban', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_h_item_5', 'area_fo_bts_sec_h', 'H.5', 'Kondisi alarm kebakaran dan detector asap di plafon normal', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_h_item_6', 'area_fo_bts_sec_h', 'H.6', 'Signage larangan merokok dan petunjuk emergency', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_h_item_7', 'area_fo_bts_sec_h', 'H.7', 'Akses pintu darurat bebas halangan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_h_item_8', 'area_fo_bts_sec_h', 'H.8', 'Buku log tamu FO BTS rapi di tempatnya', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_bts_sec_h_item_9', 'area_fo_bts_sec_h', 'H.9', 'READY TO USE: Front Office BTS Siap Operasional', 'all_checkpoints', 2, true, true, false, TRUE, 0),
('area_fo_boffice_sec_a_item_1', 'area_fo_boffice_sec_a', 'A.1', 'Lantai foyer dipel bersih, harum dan tidak licin', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_a_item_2', 'area_fo_boffice_sec_a', 'A.2', 'Tidak ada noda seretan sol sepatu atau kotoran tanah', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_a_item_3', 'area_fo_boffice_sec_a', 'A.3', 'Sambungan nat lantai bersih dan rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_a_item_4', 'area_fo_boffice_sec_a', 'A.4', 'Jalur lalu lalang tamu bebas dari halangan kabel/dus', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_a_item_5', 'area_fo_boffice_sec_a', 'A.5', 'List skriting dinding bersih dari debu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_a_item_6', 'area_fo_boffice_sec_a', 'A.6', 'Keset transisi antar ruangan kering dan bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_a_item_7', 'area_fo_boffice_sec_a', 'A.7', 'Kerapian floor drain atau penutup kabel lantai', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_a_item_8', 'area_fo_boffice_sec_a', 'A.8', 'Pemberian tanda hati-hati lantai basah bila sedang dipel', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_a_item_9', 'area_fo_boffice_sec_a', 'A.9', 'Tempat sampah tersembunyi kosong dan wangi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_a_item_10', 'area_fo_boffice_sec_a', 'A.10', 'Sirkulasi udara segar dan sejuk merata', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_1', 'area_fo_boffice_sec_b', 'B.1', 'Meja resepsionis kayu/marmer bersih tanpa noda minyak', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_2', 'area_fo_boffice_sec_b', 'B.2', 'Buku tamu / tablet digital check-in bersih & stand by', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_3', 'area_fo_boffice_sec_b', 'B.3', 'Display kartu nama & pamflet BOffice tersusun elegan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_4', 'area_fo_boffice_sec_b', 'B.4', 'Telepon PABX resepsionis bersih dan kabel rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_5', 'area_fo_boffice_sec_b', 'B.5', 'Kabel PC, printer tiket, dan monitor terbungkus pelindung', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_6', 'area_fo_boffice_sec_b', 'B.6', 'Alat tulis resepsionis lengkap di holder', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_7', 'area_fo_boffice_sec_b', 'B.7', 'Kursi ergonomis resepsionis bersih dan teratur', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_8', 'area_fo_boffice_sec_b', 'B.8', 'Dinding bawah meja bersih dari coretan sepatu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_9', 'area_fo_boffice_sec_b', 'B.9', 'Laci penyimpanan kunci loker tersusun tertib', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_b_item_10', 'area_fo_boffice_sec_b', 'B.10', 'Area belakang meja resepsionis tidak berantakan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_1', 'area_fo_boffice_sec_c', 'C.1', 'Armchair dan sofa kulit bersih tanpa debu di lipatan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_2', 'area_fo_boffice_sec_c', 'C.2', 'Meja marmer samping sofa bersih tanpa bercak cangkir', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_3', 'area_fo_boffice_sec_c', 'C.3', 'Jarak sofa lapang dan nyaman untuk privasi tamu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_4', 'area_fo_boffice_sec_c', 'C.4', 'Bantal kursi tertata rapi dan bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_5', 'area_fo_boffice_sec_c', 'C.5', 'Karpet bulu tamu sudah disedot vakum tanpa remah', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_6', 'area_fo_boffice_sec_c', 'C.6', 'Koneksi Wi-Fi tamu QR code terpasang di meja', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_7', 'area_fo_boffice_sec_c', 'C.7', 'Lampu standing lobi menyala hangat (warm white)', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_8', 'area_fo_boffice_sec_c', 'C.8', 'Tanaman indoor monstera/sansevieria daunnya dilap bersih', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_9', 'area_fo_boffice_sec_c', 'C.9', 'Tidak ada bau rokok atau apek di area lounge', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_c_item_10', 'area_fo_boffice_sec_c', 'C.10', 'Kerapian colokan charger meja lounge', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_d_item_1', 'area_fo_boffice_sec_d', 'D.1', 'Logo stainless BOffice terpasang kuat dan berkilau', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_d_item_2', 'area_fo_boffice_sec_d', 'D.2', 'Signage sub-brand BLegal bersih tanpa noda lem', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_d_item_3', 'area_fo_boffice_sec_d', 'D.3', 'Papan nama Bali Mediation Center terpasang presisi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_d_item_4', 'area_fo_boffice_sec_d', 'D.4', 'Lampu sorot spotlight logo menyala tanpa kedip', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_d_item_5', 'area_fo_boffice_sec_d', 'D.5', 'Dinding aksen kayu/batu alam bebas debu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_d_item_6', 'area_fo_boffice_sec_d', 'D.6', 'Plakat akreditasi dan izin resmi terpasang lurus', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_d_item_7', 'area_fo_boffice_sec_d', 'D.7', 'Brosur legalitas dan mediasi tersedia rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_d_item_8', 'area_fo_boffice_sec_d', 'D.8', 'Banner promosi virtual office tersusun tepat', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_d_item_9', 'area_fo_boffice_sec_d', 'D.9', 'Kerapian instalasi kelistrikan di balik panel branding', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_1', 'area_fo_boffice_sec_e', 'E.1', 'Pintu utama kaca frameless bersih dari bekas tangan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_2', 'area_fo_boffice_sec_e', 'E.2', 'Kunci digital / magnetic door lock berfungsi lancar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_3', 'area_fo_boffice_sec_e', 'E.3', 'Engsel pintu tidak berdecit dan swing normal', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_4', 'area_fo_boffice_sec_e', 'E.4', 'Stiker sandblast privasi kaca rapi tanpa gelembung', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_5', 'area_fo_boffice_sec_e', 'E.5', 'Jendela kaca samping luar bersih dan jernih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_6', 'area_fo_boffice_sec_e', 'E.6', 'Kusen aluminium bersih dari debu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_7', 'area_fo_boffice_sec_e', 'E.7', 'Gorden / roller blind bersih dan tarikan lancar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_8', 'area_fo_boffice_sec_e', 'E.8', 'Gagang pintu stainless dipoles higienis', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_9', 'area_fo_boffice_sec_e', 'E.9', 'Kamera bel pintu video bersih dan aktif', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_fo_boffice_sec_e_item_10', 'area_fo_boffice_sec_e', 'E.10', 'READY TO USE: Front Office BOffice Prima Siap Sambut Klien', 'all_checkpoints', 2, true, true, false, TRUE, 0),
('area_coworking_sec_f_item_1', 'area_coworking_sec_f', 'F.1', 'Meja sharing & dedicated desk bersih tanpa debu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_f_item_2', 'area_coworking_sec_f', 'F.2', 'Permukaan meja bebas noda kopi, pulpen, atau tip-ex', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_f_item_3', 'area_coworking_sec_f', 'F.3', 'Kotak kabel colokan di atas meja bersih dan tertutup rapat', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_f_item_4', 'area_coworking_sec_f', 'F.4', 'Semua soket listrik meja menyala normal', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_f_item_5', 'area_coworking_sec_f', 'F.5', 'Port USB / Type-C charger meja berfungsi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_f_item_6', 'area_coworking_sec_f', 'F.6', 'Nomor meja terpasang rapi dan tidak pudar', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_coworking_sec_f_item_7', 'area_coworking_sec_f', 'F.7', 'Sekat pembatas meja bersih dan kokoh', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_f_item_8', 'area_coworking_sec_f', 'F.8', 'Tempat sampah mini di bawah meja kosong & berplastik', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_f_item_9', 'area_coworking_sec_f', 'F.9', 'Tata letak meja lurus sesuai denah lantai', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_f_item_10', 'area_coworking_sec_f', 'F.10', 'Bebas dari sisa makanan atau sampah pengguna sebelumnya', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_1', 'area_coworking_sec_g', 'G.1', 'Semua kursi kerja diselaraskan menghadap meja', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_2', 'area_coworking_sec_g', 'G.2', 'Jaring/busa sandaran kursi bersih dari noda dan debu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_3', 'area_coworking_sec_g', 'G.3', 'Ketinggian hidrolik kursi berfungsi lancar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_4', 'area_coworking_sec_g', 'G.4', 'Roda kursi berputar mulus tanpa kotoran rambut terlilit', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_5', 'area_coworking_sec_g', 'G.5', 'Armrest kursi kokoh tidak goyang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_6', 'area_coworking_sec_g', 'G.6', 'Kursi cadangan tersusun rapi di area penyimpanan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_7', 'area_coworking_sec_g', 'G.7', 'Bebas dari bau tidak sedap pada bantalan kursi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_8', 'area_coworking_sec_g', 'G.8', 'Jumlah kursi sesuai kapasitas ruangan coworking', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_9', 'area_coworking_sec_g', 'G.9', 'Kerapian posisi kursi setelah sesi kerja selesai', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_g_item_10', 'area_coworking_sec_g', 'G.10', 'Pengecekan baut dan kestabilan seluruh kursi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_1', 'area_coworking_sec_h', 'H.1', 'Karpet tile coworking divakum bersih tanpa debu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_2', 'area_coworking_sec_h', 'H.2', 'Lantai vinyl area koridor dipel bersih mengkilap', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_3', 'area_coworking_sec_h', 'H.3', 'Dinding panel akustik peredam suara rapi & bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_4', 'area_coworking_sec_h', 'H.4', 'Whiteboard/kaca tulis bersih dari bekas spidol permanen', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_5', 'area_coworking_sec_h', 'H.5', 'Spidol whiteboard terisi tinta dan penghapus bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_6', 'area_coworking_sec_h', 'H.6', 'Kerapian kabel LAN dan router Wi-Fi access point', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_7', 'area_coworking_sec_h', 'H.7', 'Signage etika ketenangan (Quiet Zone) terbaca jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_8', 'area_coworking_sec_h', 'H.8', 'Suhu AC sentral sejuk stabil (22°C - 24°C)', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_9', 'area_coworking_sec_h', 'H.9', 'Diffuser aromaterapi ruangan menyala segar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_h_item_10', 'area_coworking_sec_h', 'H.10', 'Bebas dari suara bising getaran mesin/pipa', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_i_item_1', 'area_coworking_sec_i', 'I.1', 'Lampu linier gantung menyala terang dan seimbang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_i_item_2', 'area_coworking_sec_i', 'I.2', 'Plafon tidak ada sarang laba-laba atau noda bocor', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_coworking_sec_i_item_3', 'area_coworking_sec_i', 'I.3', 'Loker member bersih luar dalam dan kunci terpasang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_i_item_4', 'area_coworking_sec_i', 'I.4', 'Area phone booth kedap suara bersih dan siap pakai', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_i_item_5', 'area_coworking_sec_i', 'I.5', 'Pintu phone booth menutup rapat', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_i_item_6', 'area_coworking_sec_i', 'I.6', 'Rak buku dan majalah sharing coworking tersusun rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_i_item_7', 'area_coworking_sec_i', 'I.7', 'Kamera CCTV coworking bersih dari debu', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_coworking_sec_i_item_8', 'area_coworking_sec_i', 'I.8', 'Tempat pemilahan sampah utama coworking teratur', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coworking_sec_i_item_9', 'area_coworking_sec_i', 'I.9', 'READY TO USE: Coworking Space Siap Dipakai Member', 'all_checkpoints', 2, true, true, false, TRUE, 0),
('area_coffee_station_sec_j_item_1', 'area_coffee_station_sec_j', 'J.1', 'Mesin kopi espresso bersih dari ampas dan kerak susu', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_2', 'area_coffee_station_sec_j', 'J.2', 'Baki tetesan mesin kopi dikosongkan dan dicuci bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_3', 'area_coffee_station_sec_j', 'J.3', 'Ketel pemanas air listrik (kettle) bebas kerak air kapur', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_4', 'area_coffee_station_sec_j', 'J.4', 'Permukaan meja bar pantry kering dan bersih mengkilap', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_5', 'area_coffee_station_sec_j', 'J.5', 'Bak cuci piring (sink) stainless bersih tanpa sisa makanan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_6', 'area_coffee_station_sec_j', 'J.6', 'Spons cuci piring bersih dan sabun cuci piring tersedia', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_7', 'area_coffee_station_sec_j', 'J.7', 'Lap microfiber / kitchen towel kering dan bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_8', 'area_coffee_station_sec_j', 'J.8', 'Kulkas pantry bersih, tidak bau, dan tidak ada bunga es', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_9', 'area_coffee_station_sec_j', 'J.9', 'Microwave bersih luar dalam bebas percikan makanan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_10', 'area_coffee_station_sec_j', 'J.10', 'Tempat sampah basah pantry tertutup rapat & tidak berbau', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_11', 'area_coffee_station_sec_j', 'J.11', 'Rak pengering piring tersusun rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_12', 'area_coffee_station_sec_j', 'J.12', 'Kran air mengalir deras dan saringan sink tidak mampet', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_13', 'area_coffee_station_sec_j', 'J.13', 'Lantai dapur pantry dipel bersih dan tidak licin', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_14', 'area_coffee_station_sec_j', 'J.14', 'Kerapian kabel peralatan listrik dapur', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_15', 'area_coffee_station_sec_j', 'J.15', 'Bebas dari semut, kecoa, dan lalat buah', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_16', 'area_coffee_station_sec_j', 'J.16', 'Tutup toples bahan baku tertutup rapat higienis', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_17', 'area_coffee_station_sec_j', 'J.17', 'Signage jaga kebersihan pantry terpasang jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_coffee_station_sec_j_item_18', 'area_coffee_station_sec_j', 'J.18', 'STOK: Kopi biji / bubuk (Cukup / Menipis / Habis)', 'all_checkpoints', 1, false, true, true, TRUE, 0),
('area_coffee_station_sec_j_item_19', 'area_coffee_station_sec_j', 'J.19', 'STOK: Teh celup varian (Cukup / Menipis / Habis)', 'all_checkpoints', 1, false, true, true, TRUE, 0),
('area_coffee_station_sec_j_item_20', 'area_coffee_station_sec_j', 'J.20', 'STOK: Gula pasir & gula diet (Cukup / Menipis / Habis)', 'all_checkpoints', 1, false, true, true, TRUE, 0),
('area_coffee_station_sec_j_item_21', 'area_coffee_station_sec_j', 'J.21', 'STOK: Krimer nabati sachet/bubuk (Cukup / Menipis / Habis)', 'all_checkpoints', 1, false, true, true, TRUE, 0),
('area_coffee_station_sec_j_item_22', 'area_coffee_station_sec_j', 'J.22', 'STOK: Tisu napkin / tisu makan (Cukup / Menipis / Habis)', 'all_checkpoints', 1, false, true, true, TRUE, 0),
('area_coffee_station_sec_j_item_23', 'area_coffee_station_sec_j', 'J.23', 'STOK: Sabun cuci tangan & piring (Cukup / Menipis / Habis)', 'all_checkpoints', 1, false, true, true, TRUE, 0),
('area_coffee_station_sec_j_item_24', 'area_coffee_station_sec_j', 'J.24', 'STOK: Gelas kaca & cangkir bersih (Cukup / Menipis / Habis)', 'all_checkpoints', 1, false, true, true, TRUE, 0),
('area_coffee_station_sec_j_item_25', 'area_coffee_station_sec_j', 'J.25', 'READY TO USE: Coffee & Tea Station Bersih & Lengkap', 'all_checkpoints', 2, true, true, false, TRUE, 0),
('area_shower_sec_a_item_1', 'area_shower_sec_a', 'A.1', 'Status VACANT terpasang di pintu luar shower', 'all_checkpoints', 2, true, true, false, TRUE, 0),
('area_shower_sec_a_item_2', 'area_shower_sec_a', 'A.2', 'Handle pintu shower kokoh dan kunci grendel lancar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_3', 'area_shower_sec_a', 'A.3', 'Kaca pembatas shower cubicle bersih tanpa noda sabun/kerak air', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_4', 'area_shower_sec_a', 'A.4', 'Kran mixer shower air panas dan dingin berfungsi lancar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_5', 'area_shower_sec_a', 'A.5', 'Kepala shower (head & hand shower) lubangnya lancar tidak tersumbat kerak kapur', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_6', 'area_shower_sec_a', 'A.6', 'Lantai shower basah disikat bersih tidak berlendir/licin', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_7', 'area_shower_sec_a', 'A.7', 'Floor drain saringan shower bersih bebas dari rontokan rambut', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_8', 'area_shower_sec_a', 'A.8', 'Dinding keramik shower digosok bersih bebas jamur dan noda kuning', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_9', 'area_shower_sec_a', 'A.9', 'Tempat sabun & sampo dinding terisi penuh dan botol bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_10', 'area_shower_sec_a', 'A.10', 'Gantungan baju / handuk kering kokoh terpasang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_11', 'area_shower_sec_a', 'A.11', 'Keset bath mat kering dan lembut di depan pintu shower', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_12', 'area_shower_sec_a', 'A.12', 'Cermin shower room jernih tidak berembun atau bercak', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_13', 'area_shower_sec_a', 'A.13', 'Wastafel shower bersih dan kran air deras mengalir', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_14', 'area_shower_sec_a', 'A.14', 'Sabun cuci tangan cair di wastafel terisi penuh', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_15', 'area_shower_sec_a', 'A.15', 'Tempat sampah shower tertutup berplastik hitam & kosong', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_16', 'area_shower_sec_a', 'A.16', 'Kipas exhaust shower room menyala lancar menyedot uap', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_17', 'area_shower_sec_a', 'A.17', 'Lampu tahan air shower room menyala terang benderang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_18', 'area_shower_sec_a', 'A.18', 'Plafon shower room bersih tidak ada jamur lembab', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_19', 'area_shower_sec_a', 'A.19', 'Hair dryer di area kering berfungsi normal dan kabel rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_20', 'area_shower_sec_a', 'A.20', 'Bangku ganti baju kayu/fiber kering dan bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_21', 'area_shower_sec_a', 'A.21', 'Stop kontak area kering tertutup cover pelindung air', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_22', 'area_shower_sec_a', 'A.22', 'Kotak tisu wajah di meja wastafel terisi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_23', 'area_shower_sec_a', 'A.23', 'Aroma ruangan shower wangi segar bebas bau apek', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_24', 'area_shower_sec_a', 'A.24', 'Tidak ada tetesan bocor dari pipa atau sambungan kran', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_25', 'area_shower_sec_a', 'A.25', 'Sirkulasi udara ruangan shower segar dan tidak pengap', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_26', 'area_shower_sec_a', 'A.26', 'Kebersihan ventilasi atas shower room', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_27', 'area_shower_sec_a', 'A.27', 'Sikat pembersih lantai dan squeegee tersimpan di holder rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_28', 'area_shower_sec_a', 'A.28', 'Dinding partisi shower tidak retak atau lapuk', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_29', 'area_shower_sec_a', 'A.29', 'Kerapian silikon seal kaca shower tidak berjamur hitam', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_30', 'area_shower_sec_a', 'A.30', 'Kondisi sandal shower (jika ada) bersih dan kering', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_31', 'area_shower_sec_a', 'A.31', 'Timbangan badan digital bersih dan baterai menyala', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_32', 'area_shower_sec_a', 'A.32', 'Papan tata tertib penggunaan shower room terbaca jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_33', 'area_shower_sec_a', 'A.33', 'Kerapian gantungan perlengkapan kebersihan shower', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_34', 'area_shower_sec_a', 'A.34', 'Pintu masuk shower menutup rapat dan tidak seret', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_35', 'area_shower_sec_a', 'A.35', 'Bebas dari kecoa, kelabang, atau serangga kamar mandi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_36', 'area_shower_sec_a', 'A.36', 'Air shower jernih, tidak berbau kaporit pekat atau karat', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_37', 'area_shower_sec_a', 'A.37', 'Tekanan semprotan air shower stabil', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_38', 'area_shower_sec_a', 'A.38', 'Penyerap lembab (dehumidifier sachet) terpasang rapi', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_39', 'area_shower_sec_a', 'A.39', 'Pembersihan ceceran air di area ganti baju segera diseka', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_40', 'area_shower_sec_a', 'A.40', 'Kondisi keset karet anti-slip kokoh menempel lantai', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_shower_sec_a_item_41', 'area_shower_sec_a', 'A.41', 'SHOWER ROOM READY TO USE', 'all_checkpoints', 2, true, true, false, TRUE, 0),
('area_toilet_sec_a_item_1', 'area_toilet_sec_a', 'A.1', 'Kloset duduk disikat bersih putih mengkilap tanpa kerak urin', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_2', 'area_toilet_sec_a', 'A.2', 'Dudukan kloset (seat cover) higienis, kering dan kokoh', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_3', 'area_toilet_sec_a', 'A.3', 'Tombol dual-flush kloset berfungsi sempurna dan lancar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_4', 'area_toilet_sec_a', 'A.4', 'Jet spray bidet semprotan air kencang dan tidak bocor menetes', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_5', 'area_toilet_sec_a', 'A.5', 'Urinoir pria bersih, flush sensor otomatis menyala normal', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_6', 'area_toilet_sec_a', 'A.6', 'Saringan urinoir dan kamper aromaterapi wangi terpasang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_7', 'area_toilet_sec_a', 'A.7', 'Kertas toilet roll (jumbo roll) terpasang cukup & ada cadangan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_8', 'area_toilet_sec_a', 'A.8', 'Wastafel toilet bersih mengkilap tanpa noda pasta/sabun', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_9', 'area_toilet_sec_a', 'A.9', 'Kran wastafel otomatis/manual berfungsi deras', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_10', 'area_toilet_sec_a', 'A.10', 'Dispenser sabun cuci tangan cair terisi penuh dan higienis', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_11', 'area_toilet_sec_a', 'A.11', 'Hand dryer otomatis menyala hangat dan kencang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_12', 'area_toilet_sec_a', 'A.12', 'Dispenser tisu lap tangan terisi penuh', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_13', 'area_toilet_sec_a', 'A.13', 'Cermin wastafel besar bersih jernih tanpa noda cipratan air', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_14', 'area_toilet_sec_a', 'A.14', 'Meja counter granit wastafel kering dilap', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_15', 'area_toilet_sec_a', 'A.15', 'Tempat sampah pedal toilet wanita higienis & kantong terpasang', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_16', 'area_toilet_sec_a', 'A.16', 'Tempat sampah utama toilet tertutup rapat dan kosong', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_17', 'area_toilet_sec_a', 'A.17', 'Lantai toilet disikat bersih, wangi, kering dan tidak licin', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_18', 'area_toilet_sec_a', 'A.18', 'Nat keramik lantai toilet bersih dari lumut hitam', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_19', 'area_toilet_sec_a', 'A.19', 'Dinding keramik toilet bersih bebas bercak cipratan', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_20', 'area_toilet_sec_a', 'A.20', 'Pintu bilik toilet menutup rapat, grendel kunci berfungsi lancar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_21', 'area_toilet_sec_a', 'A.21', 'Gantungan tas/jaket di balik pintu toilet terpasang kuat', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_22', 'area_toilet_sec_a', 'A.22', 'Exhaust fan toilet menyala nonstop bebas debu tebal', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_23', 'area_toilet_sec_a', 'A.23', 'Lampu toilet menyala terang seluruh sudut bilik', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_24', 'area_toilet_sec_a', 'A.24', 'Plafon toilet bersih dari sarang laba-laba dan rembesan air', 'daily_0700', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_25', 'area_toilet_sec_a', 'A.25', 'Automatic air freshener aerosol menyemprot teratur wangi segar', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_26', 'area_toilet_sec_a', 'A.26', 'Tidak tercium bau pesing atau bau saluran pipa septic tank', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_27', 'area_toilet_sec_a', 'A.27', 'Floor drain toilet tidak tersumbat dan berbau', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_28', 'area_toilet_sec_a', 'A.28', 'Sikat pembersih kloset ditaruh rapi di wadah tertutup', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_29', 'area_toilet_sec_a', 'A.29', 'Cairan pembersih dan desinfektan tersimpan di lemari tertutup', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_30', 'area_toilet_sec_a', 'A.30', 'Papan peringatan lantai basah (wet floor sign) tersedia', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_31', 'area_toilet_sec_a', 'A.31', 'Signage toilet pria & wanita di luar pintu bersih dan jelas', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_32', 'area_toilet_sec_a', 'A.32', 'Kerapian pipa saluran air di bawah wastafel tanpa kebocoran', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_33', 'area_toilet_sec_a', 'A.33', 'Bebas dari jentik nyamuk dan serangga kecil', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_34', 'area_toilet_sec_a', 'A.34', 'Kunci master pintu bilik tersimpan aman untuk darurat', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_35', 'area_toilet_sec_a', 'A.35', 'Kondisi keset di depan pintu masuk toilet kering bersih', 'all_checkpoints', 1, false, false, false, TRUE, 0),
('area_toilet_sec_a_item_36', 'area_toilet_sec_a', 'A.36', 'TOILET ROOM READY TO USE', 'all_checkpoints', 2, true, true, false, TRUE, 0)
ON CONFLICT (id) DO NOTHING;
